from datetime import datetime
from src.database.models import Contact

contacts = [
    Contact(
        first_name="Tony",
        last_name="Stark",
        email="tony@test.com",
        phone="0981112233",
        birth_date=datetime(year=1970, month=5, day=29),
        additional="Iron Man",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    Contact(
        first_name="Bruce",
        last_name="Wayne",
        email="bruce@test.com",
        phone="0982223344",
        birth_date=datetime(year=1980, month=2, day=19),
        additional="Batman",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    Contact(
        first_name="Diana",
        last_name="Prince",
        email="diana@test.com",
        phone="0983334455",
        birth_date=datetime(year=1985, month=3, day=25),
        additional="Wonder Woman",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    Contact(
        first_name="Clark",
        last_name="Kent",
        email="clark@test.com",
        phone="0984445566",
        birth_date=datetime(year=1975, month=6, day=18),
        additional="Superman",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    Contact(
        first_name="Natasha",
        last_name="Romanoff",
        email="natasha@test.com",
        phone="0985556677",
        birth_date=datetime(year=1984, month=11, day=22),
        additional="Black Widow",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    Contact(
        first_name="Peter",
        last_name="Parker",
        email="peter@test.com",
        phone="0986667788",
        birth_date=datetime(year=2001, month=8, day=10),
        additional="Spider-Man",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    Contact(
        first_name="Stephen",
        last_name="Strange",
        email="strange@test.com",
        phone="0987778899",
        birth_date=datetime(year=1978, month=9, day=3),
        additional="Doctor Strange",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    Contact(
        first_name="Steve",
        last_name="Rogers",
        email="steve@test.com",
        phone="0988889900",
        birth_date=datetime(year=1918, month=7, day=4),
        additional="Captain America",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    Contact(
        first_name="Carol",
        last_name="Danvers",
        email="carol@test.com",
        phone="0989990011",
        birth_date=datetime(year=1987, month=10, day=17),
        additional="Captain Marvel",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    Contact(
        first_name="T'Challa",
        last_name="Black Panther",
        email="tchalla@test.com",
        phone="0980001122",
        birth_date=datetime(year=1980, month=12, day=1),
        additional="King of Wakanda",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
]
